import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
	title: 'Juan Pablo Canedo Portfolio',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={` ${inter.className}  bg-zinc-950 text-white`}>
				<Header />
				{children}
			</body>
		</html>
	);
}
